#1/559BUG6E_jizKM5ycbaaDScFWsTVoeOO0sEcJES9IwA
version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-
      
      - run:
          name: Install Dependencies
          command: npm install

      - save_cache: 
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
            
          paths:
            - ./node_modules          

      - run:
          name: Vue Build
          command: npm run build
      
      - run:
          name: Firebase Deploy
          command: firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token=$FIREBASE_TOKEN