#1/559BUG6E_jizKM5ycbaaDScFWsTVoeOO0sEcJES9IwA
version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8
    working_directory: ~/portfolio
    steps:
      # Checkout the code from the branch into the working_directory
      - checkout
      # Restore local dependencies from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache: 
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules          
      - run:
          name: Vue Build
          command: npm run build
      # Cache the dist folder for the deploy job
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
              - dist

  deploy-prod:
    docker:
      - image: circleci/node:8
    working_directory: /tmp/portfolio
    steps:
      # Restore cache from the build job which contains the
      # dist folder that needs to be deployed
      - restore_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Installing firebase-tools
          command: npm install firebase-tools
      - run:
          name: Firebase Deploy if tests pass and branch is Master
          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive

workflows:
  version: 2
  cd:
    jobs:
        - build:
            filters:
              branches:
                ignore:
                  -dev
                  - /feature-.*/
        - deploy-prod:
            requires:
              - build
            filters:
              branches:
                only:
                - master